### ISSUE TITLE
Question: I can't seem to find out how to get working

### ISSUE THREAD

**Issue by DBojsen** [mogular/wp-powerbicodeformatter#1]
Hi

Sorry for the newbie question, but I'm very new to Wordpress.
I have a site on latest version of WP and have installed your plugin, but cannot find out how to use it.

Any chance you could provide step-by-step guide?

BR David

**Comment by andreasmo** [comment]
Hi David
the plugin works with very simple shortcodes. [Here you find a short intro to shortcodes.](https://www.wpbeginner.com/wp-tutorials/how-to-add-a-shortcode-in-wordpress/). The supported shortcodes are shown on the [plugin homepage](https://wordpress.org/plugins/code-formatter-for-powerbi/).
You just add a shortcode in your post where you want your formatted code shown.
Hope that helps.
Andreas

**Comment by DBojsen** [comment]
Hi Andreas

Thank you - appreciate it.
Have a great day.

/ David
